### ISSUE TITLE
Missing expected options

### ISSUE THREAD

**Issue by evanniedojadlo** [RailsApps/rails-bootstrap#23]
I am currently following along the "rails-mailinglist-activejob" tutorial which makes use of the rails-bootstrap installation. I noted within the tutorial that we should expect the following prompt but this prompt never occurred within the composer tool:

"Use or create a project-specific rvm gemset? yes"

Note that this did not cause an issue but was not present and went immediately into gem installation after I selected "No" for "Create a GitHub repository?"

**Comment by DanielKehoe** [comment]
Do you have RVM installed?
```
$ rvm -v
```

**Comment by evanniedojadlo** [comment]
@DanielKehoe Yes, RVM had already been installed within the environment.

**Comment by DanielKehoe** [comment]
Not sure why you are not seeing the prompt. Post the full console output and maybe I'll see something. It's likely a local development enviroment issue as no one else has reported this.

**Comment by evanniedojadlo** [comment]
Understood thanks, also the following contains the full console output:

Initialized empty Git repository in /Users/RAI/Desktop/Projects/MB_Launcher/.git/
         run    git add -A from "."
         run    git commit -qm "rails_apps_composer: initial commit" from "."
      recipe  Running railsapps recipe...
      option  Build a starter application?
          1)  Build a RailsApps example application
          2)  Contributed applications (none available)
          3)  Custom application (experimental)
      choose  Enter your selection: 1
      option  Choose a starter application.
          1)  learn-rails
          2)  rails-bootstrap
          3)  rails-foundation
          4)  rails-mailinglist-activejob
          5)  rails-omniauth
          6)  rails-devise
          7)  rails-devise-roles
          8)  rails-devise-pundit
          9)  rails-signup-download
         10)  rails-stripe-checkout
         11)  rails-stripe-coupons
      choose  Enter your selection: 2
              Get on the mailing list for Rails Composer news?
      option  Enter your email address:
      recipe  Running learn_rails recipe...
      recipe  Running rails_bootstrap recipe...
      recipe  Running rails_foundation recipe...
      recipe  Running rails_omniauth recipe...
      recipe  Running rails_devise recipe...
      recipe  Running rails_devise_roles recipe...
      recipe  Running rails_devise_pundit recipe...
      recipe  Running rails_signup_download recipe...
      recipe  Running rails_mailinglist_activejob recipe...
      recipe  Running rails_stripe_checkout recipe...
      recipe  Running rails_stripe_coupons recipe...
      recipe  Running setup recipe...
       setup  Your operating system is darwin13.1.0.
       setup  You are using Ruby version 2.1.1.
       setup  You are using Rails version 4.2.0.
      option  Web server for development?
          1)  WEBrick (default)
          2)  Thin
          3)  Unicorn
          4)  Puma
          5)  Phusion Passenger (Apache/Nginx)
          6)  Phusion Passenger (Standalone)
      choose  Enter your selection: 1
      option  Web server for production?
          1)  Same as development
          2)  Thin
          3)  Unicorn
          4)  Puma
          5)  Phusion Passenger (Apache/Nginx)
          6)  Phusion Passenger (Standalone)
      choose  Enter your selection: 1
      option  Database used in development?
          1)  SQLite
          2)  PostgreSQL
          3)  MySQL
      choose  Enter your selection: 1
      option  Template engine?
          1)  ERB
          2)  Haml
          3)  Slim
      choose  Enter your selection: 1
      option  Test framework?
          1)  None
          2)  RSpec with Capybara
      choose  Enter your selection: 2
       setup  Adding DatabaseCleaner, FactoryGirl, Faker, Launchy, Selenium
      option  Continuous testing?
          1)  None
          2)  Guard
      choose  Enter your selection: 1
      option  Use a form builder gem?
          1)  None
          2)  SimpleForm
      choose  Enter your selection: 2
      create    README
      append    README
      recipe  Running locale recipe...
      recipe  Running readme recipe...
      recipe  Running gems recipe...
      insert    Gemfile
        gsub    Gemfile
        gsub    Gemfile
        gsub    Gemfile
         run    git add -A from "."
         run    git commit -qm "rails_apps_composer: Gemfile" from "."
      recipe  Running tests recipe...
      recipe  Running email recipe...
      recipe  Running devise recipe...
      recipe  Running omniauth recipe...
      recipe  Running roles recipe...
      recipe  Running frontend recipe...
      recipe  Running pages recipe...
      recipe  Running init recipe...
      recipe  Running analytics recipe...
      option  Install page-view analytics?
          1)  None
          2)  Google Analytics
          3)  Segment.io
      choose  Enter your selection: 1
      recipe  Running deployment recipe...
      option  Prepare for deployment?
          1)  no
          2)  Heroku
          3)  Capistrano
      choose  Enter your selection: 1
      recipe  Running extras recipe...
      option  Set a robots.txt file to ban spiders? (y/n) n
      option  Create a GitHub repository? (y/n) n
      extras  recipe setting quiet_assets for reduced asset pipeline logging
      extras  recipe adding better_errors gem
    composer  Installing gems. This will take a while.
         run    bundle install --without production from "."
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Using rake 10.4.2
Using i18n 0.7.0
Using json 1.8.2
Using minitest 5.5.1
Using thread_safe 0.3.4
Using tzinfo 1.2.2
Using activesupport 4.2.0
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile 0.6.2
Using nokogiri 1.6.6.2
Using rails-deprecated_sanitizer 1.0.3
Using rails-dom-testing 1.0.5
Using loofah 2.0.1
Using rails-html-sanitizer 1.0.1
Using actionview 4.2.0
Using rack 1.6.0
Using rack-test 0.6.3
Using actionpack 4.2.0
Using globalid 0.3.2
Using activejob 4.2.0
Installing mime-types 2.4.3
Installing mail 2.6.3
Using actionmailer 4.2.0
Using activemodel 4.2.0
Using arel 6.0.0
Using activerecord 4.2.0
Installing addressable 2.3.7
Installing execjs 2.3.0
Installing autoprefixer-rails 5.1.5
Using coderay 1.1.0
Using better_errors 2.1.1
Using debug_inspector 0.0.2
Using binding_of_caller 0.7.2
Installing sass 3.4.11
Installing bootstrap-sass 3.3.3
Using bundler 1.7.12
Installing columnize 0.9.0
Installing debugger-linecache 1.2.0
Installing slop 3.6.0
Installing byebug 3.5.1
Using xpath 2.0.0
Installing capybara 2.4.4
Installing ffi 1.9.6
Installing childprocess 0.5.5
Installing coffee-script-source 1.9.0
Using coffee-script 2.3.0
Using thor 0.19.1
Using railties 4.2.0
Installing coffee-rails 4.1.0
Installing database_cleaner 1.4.0
Using diff-lcs 1.2.5
Installing factory_girl 4.5.0
Installing factory_girl_rails 4.5.0
Installing faker 1.4.3
Using high_voltage 2.2.1
Using hike 1.2.3
Using multi_json 1.10.1
Using jbuilder 2.2.6
Installing jquery-rails 4.0.3
Using launchy 2.4.3
Using quiet_assets 1.1.0
Using tilt 1.4.1
Using sprockets 2.12.3
Using sprockets-rails 2.2.4
Using rails 4.2.0
Using rails_apps_pages 0.5.15
Installing rails_apps_testing 0.3.12
Using rails_layout 1.0.24
Installing rspec-support 3.2.1
Installing rspec-core 3.2.0
Installing rspec-expectations 3.2.0
Installing rspec-mocks 3.2.0
Installing rspec-rails 3.2.0
Installing rubyzip 1.1.7
Installing sass-rails 5.0.1
Using websocket 1.2.1
Installing selenium-webdriver 2.44.0
Using simple_form 3.1.0
Installing spring 1.3.1
Installing spring-commands-rspec 1.0.4
Using sqlite3 1.3.10
Using turbolinks 2.5.3
Using uglifier 2.7.0
Installing web-console 2.0.0
Your bundle is complete!
Gems in the group production were not installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
    composer  Updating gem paths.
WARN: Unresolved specs during Gem::Specification.reset:
      json (>= 1.7.7, ~> 1.7)
      rack-test (~> 0.6.2)
      nokogiri (>= 1.5.9, ~> 1.6.0)
      builder (~> 3.1)
      rake (>= 0.8.7)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
    composer  Stage Two (running recipe 'stage_two' callbacks).
locale
gems
        gems  recipe stage two
        gems  configuring database
gems
        gems  recipe stage two
        gems  running generators
        gems  recipe installing simple_form for use with Bootstrap
    generate    simple_form:install --bootstrap
[Simple Form] Simple Form is not configured in the application and will use the default values. Use `rails generate simple_form:install` to generate the Simple Form configuration.
      create  config/initializers/simple_form.rb
      create  config/initializers/simple_form_bootstrap.rb
       exist  config/locales
      create  config/locales/simple_form.en.yml
      create  lib/templates/erb/scaffold/_form.html.erb
===============================================================================

  Be sure to have a copy of the Bootstrap stylesheet available on your
  application, you can get it on http://getbootstrap.com/.

  Inside your views, use the 'simple_form_for' with one of the Bootstrap form
  classes, '.form-horizontal' or '.form-inline', as the following:

    = simple_form_for(@user, html: { class: 'form-horizontal' }) do |form|

===============================================================================
         run    git add -A from "."
         run    git commit -qm "rails_apps_composer: generators" from "."
tests
       tests  recipe stage two
       tests  recipe installing RSpec
    generate    testing:configure rspec -f
         run  rm -rf test/ from "."
    generate  rspec:install
      create  .rspec
      create  spec
      create  spec/spec_helper.rb
      create  spec/rails_helper.rb
      insert  .rspec
      insert  .rspec
        gsub  .rspec
      insert  config/application.rb
      create  spec/support/capybara.rb
        gsub  spec/rails_helper.rb
        gsub  spec/rails_helper.rb
      create  spec/support/database_cleaner.rb
      create  spec/support/factory_girl.rb
         run    git add -A from "."
         run    git commit -qm "rails_apps_composer: testing framework" from "."
email
       email  recipe stage two
         run    git add -A from "."
         run    git commit -qm "rails_apps_composer: set email accounts" from "."
On branch master
nothing to commit, working directory clean
devise
      devise  recipe stage two
         run    git add -A from "."
         run    git commit -qm "rails_apps_composer: devise" from "."
On branch master
nothing to commit, working directory clean
omniauth
    omniauth  recipe stage two
         run    git add -A from "."
         run    git commit -qm "rails_apps_composer: omniauth" from "."
On branch master
nothing to commit, working directory clean
roles
       roles  recipe stage two
         run    git add -A from "."
         run    git commit -qm "rails_apps_composer: add roles to a User model" from "."
On branch master
nothing to commit, working directory clean
frontend
    frontend  recipe stage two
    generate    layout:install bootstrap3 -f
      remove  app/assets/stylesheets/application.css
      create  app/assets/stylesheets/application.css.scss
      create  app/assets/stylesheets/framework_and_overrides.css.scss
       force  app/assets/javascripts/application.js
      remove  app/assets/stylesheets/simple.css
      remove  app/assets/stylesheets/foundation_and_overrides.css.scss
      remove  app/views/layouts/application.html.erb
      create  app/views/layouts/application.html.erb
      create  app/views/layouts/_messages.html.erb
      create  app/views/layouts/_navigation.html.erb
      create  app/views/layouts/_navigation_links.html.erb
         run    git add -A from "."
         run    git commit -qm "rails_apps_composer: front-end framework" from "."
pages
       pages  recipe stage two
    generate    pages:about -f
    generate  pages:home -f
      create  app/views/visitors/index.html.erb
      create  app/controllers/visitors_controller.rb
      insert  config/routes.rb
      create  spec/features/visitors/home_page_spec.rb
      create  app/views/pages/about.html.erb
      create  spec/features/visitors/about_page_spec.rb
    generate    layout:navigation -f
   identical  app/views/layouts/_navigation_links.html.erb
      append  app/views/layouts/_navigation_links.html.erb
         run    git add -A from "."
         run    git commit -qm "rails_apps_composer: add pages" from "."
analytics
   analytics  recipe stage two
         run    git add -A from "."
         run    git commit -qm "rails_apps_composer: add analytics" from "."
On branch master
nothing to commit, working directory clean
    composer  Stage Three (running recipe 'stage_three' callbacks).
readme
      readme  recipe stage three
      remove    README
      remove    README.rdoc
      remove    doc/README_FOR_APP
      create    README
      append    README
      append    README
      create    public/humans.txt
      create    README.md
      append    README.md
         run    git add -A from "."
         run    git commit -qm "rails_apps_composer: add README files" from "."
tests
       tests  recipe stage three
      remove    spec/features/users/user_index_spec.rb
      remove    spec/features/users/user_show_spec.rb
init
        init  recipe stage three
      insert    config/secrets.yml
      insert    config/secrets.yml
      insert    config/secrets.yml
         run    bundle exec rake db:seed from "."
         run    git add -A from "."
         run    git commit -qm "rails_apps_composer: set up database" from "."
    generate    layout:navigation -f
       force  app/views/layouts/_navigation_links.html.erb
      append  app/views/layouts/_navigation_links.html.erb
         run    git add -A from "."
         run    git commit -qm "rails_apps_composer: navigation links" from "."
On branch master
nothing to commit, working directory clean
deployment
         run    git add -A from "."
         run    git commit -qm "rails_apps_composer: prepare for deployment" from "."
On branch master
nothing to commit, working directory clean
extras
      extras  recipe stage three
      extras  recipe removing unnecessary files and whitespace
      remove    public/index.html
      remove    app/assets/images/rails.png
        gsub    Gemfile
        gsub    Gemfile
        gsub    Gemfile
        gsub    Gemfile
      remove    Gemfile.lock
         run    bundle install --without production from "."
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Using rake 10.4.2
Using i18n 0.7.0
Using json 1.8.2
Using minitest 5.5.1
Using thread_safe 0.3.4
Using tzinfo 1.2.2
Using activesupport 4.2.0
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile 0.6.2
Using nokogiri 1.6.6.2
Using rails-deprecated_sanitizer 1.0.3
Using rails-dom-testing 1.0.5
Using loofah 2.0.1
Using rails-html-sanitizer 1.0.1
Using actionview 4.2.0
Using rack 1.6.0
Using rack-test 0.6.3
Using actionpack 4.2.0
Using globalid 0.3.2
Using activejob 4.2.0
Using mime-types 2.4.3
Using mail 2.6.3
Using actionmailer 4.2.0
Using activemodel 4.2.0
Using arel 6.0.0
Using activerecord 4.2.0
Using addressable 2.3.7
Using execjs 2.3.0
Using autoprefixer-rails 5.1.5
Using coderay 1.1.0
Using better_errors 2.1.1
Using debug_inspector 0.0.2
Using binding_of_caller 0.7.2
Using sass 3.4.11
Using bootstrap-sass 3.3.3
Using bundler 1.7.12
Using columnize 0.9.0
Using debugger-linecache 1.2.0
Using slop 3.6.0
Using byebug 3.5.1
Using xpath 2.0.0
Using capybara 2.4.4
Using ffi 1.9.6
Using childprocess 0.5.5
Using coffee-script-source 1.9.0
Using coffee-script 2.3.0
Using thor 0.19.1
Using railties 4.2.0
Using coffee-rails 4.1.0
Using database_cleaner 1.4.0
Using diff-lcs 1.2.5
Using factory_girl 4.5.0
Using factory_girl_rails 4.5.0
Using faker 1.4.3
Using high_voltage 2.2.1
Using hike 1.2.3
Using multi_json 1.10.1
Using jbuilder 2.2.6
Using jquery-rails 4.0.3
Using launchy 2.4.3
Using quiet_assets 1.1.0
Using tilt 1.4.1
Using sprockets 2.12.3
Using sprockets-rails 2.2.4
Using rails 4.2.0
Using rails_layout 1.0.24
Using rspec-support 3.2.1
Using rspec-core 3.2.0
Using rspec-expectations 3.2.0
Using rspec-mocks 3.2.0
Using rspec-rails 3.2.0
Using rubyzip 1.1.7
Using sass-rails 5.0.1
Using websocket 1.2.1
Using selenium-webdriver 2.44.0
Using simple_form 3.1.0
Using spring 1.3.1
Using spring-commands-rspec 1.0.4
Using sqlite3 1.3.10
Using turbolinks 2.5.3
Using uglifier 2.7.0
Using web-console 2.0.0
Your bundle is complete!
Gems in the group production were not installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
        gsub    config/routes.rb
        gsub    config/routes.rb
         run    git add -A from "."
         run    git commit -qm "rails_apps_composer: extras" from "."
    composer  Your new application will contain diagnostics in its README file.
    composer  When reporting an issue on GitHub, include the README diagnostics.
    composer  Finished running the rails_apps_composer app template.
    composer  Your new Rails app is ready. Time to run 'bundle install'.
         run  bundle install
Using rake 10.4.2
Using i18n 0.7.0
Using json 1.8.2
Using minitest 5.5.1
Using thread_safe 0.3.4
Using tzinfo 1.2.2
Using activesupport 4.2.0
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile 0.6.2
Using nokogiri 1.6.6.2
Using rails-deprecated_sanitizer 1.0.3
Using rails-dom-testing 1.0.5
Using loofah 2.0.1
Using rails-html-sanitizer 1.0.1
Using actionview 4.2.0
Using rack 1.6.0
Using rack-test 0.6.3
Using actionpack 4.2.0
Using globalid 0.3.2
Using activejob 4.2.0
Using mime-types 2.4.3
Using mail 2.6.3
Using actionmailer 4.2.0
Using activemodel 4.2.0
Using arel 6.0.0
Using activerecord 4.2.0
Using addressable 2.3.7
Using execjs 2.3.0
Using autoprefixer-rails 5.1.5
Using coderay 1.1.0
Using better_errors 2.1.1
Using debug_inspector 0.0.2
Using binding_of_caller 0.7.2
Using sass 3.4.11
Using bootstrap-sass 3.3.3
Using columnize 0.9.0
Using debugger-linecache 1.2.0
Using slop 3.6.0
Using byebug 3.5.1
Using xpath 2.0.0
Using capybara 2.4.4
Using ffi 1.9.6
Using childprocess 0.5.5
Using coffee-script-source 1.9.0
Using coffee-script 2.3.0
Using thor 0.19.1
Using railties 4.2.0
Using coffee-rails 4.1.0
Using database_cleaner 1.4.0
Using diff-lcs 1.2.5
Using factory_girl 4.5.0
Using factory_girl_rails 4.5.0
Using faker 1.4.3
Using high_voltage 2.2.1
Using hike 1.2.3
Using multi_json 1.10.1
Using jbuilder 2.2.6
Using jquery-rails 4.0.3
Using launchy 2.4.3
Using quiet_assets 1.1.0
Using bundler 1.7.12
Using tilt 1.4.1
Using sprockets 2.12.3
Using sprockets-rails 2.2.4
Using rails 4.2.0
Using rails_layout 1.0.24
Using rspec-support 3.2.1
Using rspec-core 3.2.0
Using rspec-expectations 3.2.0
Using rspec-mocks 3.2.0
Using rspec-rails 3.2.0
Using rubyzip 1.1.7
Using sass-rails 5.0.1
Using websocket 1.2.1
Using selenium-webdriver 2.44.0
Using simple_form 3.1.0
Using spring 1.3.1
Using spring-commands-rspec 1.0.4
Using sqlite3 1.3.10
Using turbolinks 2.5.3
Using uglifier 2.7.0
Using web-console 2.0.0
Your bundle is complete!
Gems in the group production were not installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
         run  bundle exec spring binstub --all
* bin/rake: spring inserted
* bin/rspec: generated with spring
* bin/rails: spring inserted

**Comment by DanielKehoe** [comment]
I'm using 
```
       setup  Your operating system is darwin14.0.0.
       setup  You are using Ruby version 2.2.0.
       setup  You are using Rails version 4.2.0.
```
and I can't duplicate the issue.

**Comment by evanniedojadlo** [comment]
@DanielKehoe Thanks, I ran another installation as a test and returned the "Use or create a project-specific rvm gemset?" question without issue now. Closing out.
