### ISSUE TITLE
 Ruby version is 2.2.2, but your Gemfile specified 2.2.3

### ISSUE THREAD

**Issue by tomelam** [RailsApps/rails-bootstrap#26]
The file .ruby-version specifies Ruby version 2.2.2, but the Gemfile specifies 2.2.3. Thus when I 'cd' into the directory and try 'bundle install', I get the error 'Your Ruby version is 2.2.2, but your Gemfile specified 2.2.3'.

**Comment by tomelam** [comment]
Hi, Daniel. Then I suppose I'll edit .ruby-version and be done with it. Should I try to push that?

**Comment by DanielKehoe** [comment]
I'll make the fix. Thanks for pointing out the issue.

**Comment by tomelam** [comment]
Thanks.
